name: Auto Update FinSEO Site

on:
  schedule:
    - cron: '5 16 * * *'
  workflow_dispatch:

permissions:
  contents: write

jobs:
  build_and_deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Проверяем код
      uses: actions/checkout@v4

    - name: Устанавливаем Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.10'

    - name: Библиотеки
      run: pip install pandas requests jinja2

    - name: Запуск робота
      run: python run_finseo.py

    - name: Деплой
      run: |
        git config --global user.name "FinSeoBot"
        git config --global user.email "bot@finseo.ru"
        git add index.html
        git commit -m "Авто-обновление ОФЗ" || echo "Изменений нет"
        git push
